name: Run Unit Tests

on:
  push:
    branches:
      - main # Replace with your branch name
  pull_request:
    branches:
      - main # Replace with your branch name

jobs:
  unit-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
